version: "3.9"
services:
  pgdb:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env.postgres
    ports:
    - "5432:5432"
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    env_file:
      - .env.pgadmin
    depends_on:
      - pgdb
    ports:
    - "5050:80"
  notebook:
    container_name: notebook
    image: jupyter/scipy-notebook
    ports:
    - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "jupyter"
    volumes:
      - ./code:/home/jovyan/work
  python-code:
    container_name: pycode
    build: ./code
    depends_on:
      - pgdb
    ports:
    - "5000:5000"
    volumes:
      - ./code:/pycode/code
    entrypoint: ["python3", "country_api.py"]

